name: Publish Artifacts

on:
  schedule:
    - cron: '0 7 * * *'   # placeholder schedule (adjust later)
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c(
            "devtools", "dplyr", "arrow", "readr", "qs", "rstan", "brms", "fs"
          ), repos="https://cloud.r-project.org")'
      - name: Run ETL (placeholder)
        run: |
          Rscript data-raw/update_all_data.R
      # Next steps (checkout public repo, copy artifacts) will be added later
