name: Update Data and Sync to App Repo

on:
  schedule:
    - cron: '15 8 * * *'    # Every day at 08:15 UTC (adjust as needed)
  workflow_dispatch:

jobs:
  build-and-sync:
    runs-on: ubuntu-latest

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install R package dependencies
        run: |
          Rscript -e 'install.packages(c(
            "arrow", "qs", "dplyr", "tibble", "purrr", "glue", "fs", "stringr",
            "tidyr", "slider", "nflfastR", "nflreadr", "nflseedR", "readr"
          ))'
          Rscript -e 'install.packages(".", repos = NULL, type = "source")'

      - name: Run ETL pipeline
        run: Rscript data-raw/update_all_data.R

      - name: Checkout app repo (public, as subfolder)
        uses: actions/checkout@v4
        with:
          repository: tylerpollard410/nflanalysisapp
          ref: main
          token: ${{ secrets.PUSH_TOKEN }}
          path: nflanalysisapp

      - name: Sync only .parquet files to app repo data/
        run: |
          mkdir -p nflanalysisapp/data
          rsync -av --include '*/' --include '*.parquet' --exclude '*' artifacts/data/ nflanalysisapp/data/

      - name: Commit and push updated data to app repo
        working-directory: nflanalysisapp
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/
          git commit -m "Update data artifacts [skip ci]" || echo "No changes to commit"
          git push origin main
